// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using S00254903_ConsoleApp;

#nullable disable

namespace S00254903_ConsoleApp.Migrations
{
    [DbContext(typeof(ConsoleStudentContext))]
    [Migration("20260105152756_MakeLecturerIDNullable")]
    partial class MakeLecturerIDNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CourseStudent", b =>
                {
                    b.Property<int>("CoursesID")
                        .HasColumnType("int");

                    b.Property<int>("StudentsID")
                        .HasColumnType("int");

                    b.HasKey("CoursesID", "StudentsID");

                    b.HasIndex("StudentsID");

                    b.ToTable("CourseStudent");
                });

            modelBuilder.Entity("S00254903_ClassLibrary.Course", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LecturerID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QQILevel")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("LecturerID");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Description = "blah blah for loop",
                            LecturerID = 2,
                            Name = "Introduction to Programming",
                            QQILevel = 6
                        },
                        new
                        {
                            ID = 2,
                            Description = "Relational DBs are superior",
                            LecturerID = 1,
                            Name = "Advanced Databases",
                            QQILevel = 7
                        });
                });

            modelBuilder.Entity("S00254903_ClassLibrary.Lecturer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Lecturers");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Email = "otto@atu.ie",
                            FirstName = "Otto",
                            Surname = "Octavius",
                            Title = "Dr."
                        },
                        new
                        {
                            ID = 2,
                            Email = "dominic.carr@atu.ie",
                            FirstName = "Dominic",
                            Surname = "Carr",
                            Title = "Dr."
                        });
                });

            modelBuilder.Entity("S00254903_ClassLibrary.Student", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Eircode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Age = 22,
                            Eircode = "A94 FP71",
                            Email = "jammyboi@yahoo.com",
                            FirstName = "James",
                            Surname = "Johnson"
                        },
                        new
                        {
                            ID = 2,
                            Age = 45,
                            Eircode = "D14 X3H0",
                            Email = "spider-man@marvel.com",
                            FirstName = "Peter",
                            Surname = "Parker"
                        },
                        new
                        {
                            ID = 3,
                            Age = 78,
                            Eircode = "D07 Y3B0",
                            Email = "thedonald45@usa.com",
                            FirstName = "Donald",
                            Surname = "Trump"
                        });
                });

            modelBuilder.Entity("CourseStudent", b =>
                {
                    b.HasOne("S00254903_ClassLibrary.Course", null)
                        .WithMany()
                        .HasForeignKey("CoursesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("S00254903_ClassLibrary.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("S00254903_ClassLibrary.Course", b =>
                {
                    b.HasOne("S00254903_ClassLibrary.Lecturer", "Lecturer")
                        .WithMany("Courses")
                        .HasForeignKey("LecturerID");

                    b.Navigation("Lecturer");
                });

            modelBuilder.Entity("S00254903_ClassLibrary.Lecturer", b =>
                {
                    b.Navigation("Courses");
                });
#pragma warning restore 612, 618
        }
    }
}
